name: Build and deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '14'
      - name: Versions
        run: |
          echo "Node:"
          node --version
          echo "NPM:"
          npm --version
          echo "Git:"
          git --version
      - name: Install dependencies
        run: npm i
      - name: Install Gulp
        run: |
          npm i gulp-cli -g
          gulp --version
      - name: Build
        run: gulp build --production
      - name: Upload bundle
        uses: actions/upload-artifact@master
        with:
          name: bundle
          path: dist
      - name: Debug
        run: ls
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download bundle
        uses: actions/download-artifact@master
        with:
          name: bundle
          path: dist
      - name: Debug
        run: ls
      - name: Upload to FTP
        uses: isthatcentered/dist-to-ftp@master
        with:
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          host: ${{ secrets.FTP_HOST }}
          path: dist
          into: ${{ secrets.FTP_REMOTE_DIR }}
          cleanupExisting: true
